# Generated by Django 6.0.1 on 2026-05-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Leselystapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
