# Generated by Django 6.0.1 on 2026-06-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Leselystapp", "0004_readingchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingchallenge",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
