# Generated by Django 6.0.1 on 2026-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Leselystapp", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="buy_url_amazon",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="buy_url_ark",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="buy_url_norli",
            field=models.URLField(blank=True, null=True),
        ),
    ]
